[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts']
# could set this to true
via-ir = false
# optimizer_runs = 2000
ffi = true
evm_version = "shanghai"

[profile.zksync]
src = 'src'
libs = ['lib']
fallback_oz = true
mode = "3"

[fuzz]
runs = 200
# At least 25% of tests should not be rejected
max_test_rejects = 150
seed = '0x1'
dictionary_weight = 40
include_storage = true
include_push_bytes = true
extra_output = ["storageLayout", "metadata"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
